#!/bin/bash
QUERY="http://192.168.1.130/iZoneRequestV2"
COMMAND="http://192.168.1.130/iZoneCommandV2"

case "$1" in
    on|ON)
        curl -v -XPOST "$COMMAND"  -H "Content-Type: application/json" --data '{"SysOn":1}'
    ;;
    off|OFF)
        curl -v -XPOST "$COMMAND" -H "Content-Type: application/json" --data '{"SysOn":0}'
    ;;
    info|stat|status|STATUS)
        curl "$QUERY" -H "Content-Type: application/json" --data \
        '{
            "iZoneV2Request": {
                "Type": 1,
                "No": 0,
                "No1": 0
                }
        }'|jq
    ;;
    kitchen)
        case "$2" in
        stat|status)
            curl "$QUERY" -H "Content-Type: application/json" --data \
            '{
                "iZoneV2Request": {
                    "Type": 2,
                    "No": 0,
                    "No1": 0
                    }
            }'|jq
        ;;
        on)
            curl -v -XPOST "$COMMAND"  -H "Content-Type: application/json" --data '{"ZoneMode":{"Index":0,"Mode":3}}'
        ;;
        off)
            curl -v -XPOST "$COMMAND"  -H "Content-Type: application/json" --data '{"ZoneMode":{"Index":0,"Mode":2}}'
        ;;
        *)
            echo -e "Invalid"
        ;;
        esac
    ;;
    theatre)
        curl "$QUERY" -H "Content-Type: application/json" --data \
        '{
            "iZoneV2Request": {
                "Type": 2,
                "No": 1,
                "No1": 0
                }
        }'|jq
    ;;
    living)
        curl "$QUERY" -H "Content-Type: application/json" --data \
        '{
            "iZoneV2Request": {
                "Type": 2,
                "No": 2,
                "No1": 0
                }
        }'|jq
    ;;
    master)
        curl "$QUERY" -H "Content-Type: application/json" --data \
        '{
            "iZoneV2Request": {
                "Type": 2,
                "No": 3,
                "No1": 0
                }
        }'|jq
    ;;
    work)
        curl "$QUERY" -H "Content-Type: application/json" --data \
        '{
            "iZoneV2Request": {
                "Type": 2,
                "No": 4,
                "No1": 0
                }
        }'|jq
    ;;
    guest)
        curl "$QUERY" -H "Content-Type: application/json" --data \
        '{
            "iZoneV2Request": {
                "Type": 2,
                "No": 5,
                "No1": 0
                }
        }'|jq
    ;;
    rayden)
        curl "$QUERY" -H "Content-Type: application/json" --data \
        '{
            "iZoneV2Request": {
                "Type": 2,
                "No": 6,
                "No1": 0
                }
        }'|jq
    ;;
    rumpus)
        curl "$QUERY" -H "Content-Type: application/json" --data \
        '{
            "iZoneV2Request": {
                "Type": 2,
                "No": 7,
                "No1": 0
                }
        }'|jq
    ;;
    *)
        echo -e "Invalid."
esac



